server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 5432
  user:
  password:
  dbname:
  sslmode: disable
  max_conns: 10
  min_conns: 2

max_bot:
  token: ""
  chat_id: ""
  active: false

uploads:
  path: ./uploads
  max_size_mb: 10
